export const CONTACTS_TYPES = {
  GET_CONTACT: 'GET_CONTACT',
  GET_CONTACT_SUCCESS: 'GET_CONTACT_SUCCESS',
  GET_ALL_CONTACTS: 'GET_ALL_CONTACTS',
  GET_ALL_CONTACTS_SUCCESS: 'GET_ALL_CONTACTS_SUCCESS',
  CREATE_CONTACT: 'CREATE_CONTACT',
  CREATE_CONTACT_SUCCESS: 'CREATE_CONTACT_SUCCESS',
  UPDATE_CONTACT: 'UPDATE_CONTACT',
  UPDATE_CONTACT_SUCCESS: 'UPDATE_CONTACT_SUCCESS',
  DELETE_CONTACT: 'DELETE_CONTACT',
  DELETE_CONTACT_SUCCESS: 'DELETE_CONTACT_SUCCESS',
  ON_FAILURE: 'ON_FAILURE',
};
